### PR TITLE
Fix liblo 0.32 header compatibility

### LINKED ISSUE #1949: build error: OSCNode.cpp:153:28: error: cannot convert 'lo_arg*' to 'lo_blob' {aka 'lo_blob_*'} in initialization
I get 

```
plugins/osc/OSCNode.cpp: In function 'int ola::plugin::osc::OSCDataHandler(const char*, const char*, lo_arg**, int, void*, void*)':
plugins/osc/OSCNode.cpp:153:28: error: cannot convert 'lo_arg*' to 'lo_blob' {aka 'lo_blob_*'} in initialization
  153 |       lo_blob blob = argv[0];
      |                      ~~~~~~^
      |                            |
      |                            lo_arg*
plugins/osc/OSCNode.cpp: In member function 'bool ola::plugin::osc::OSCNode::Init()':
plugins/osc/OSCNode.cpp:266:50: error: invalid conversion from 'int (*)(const char*, const char*, lo_arg**, int, void*, void*)' to 'lo_method_handler' {aka 'int (*)(const char*, const char*, lo_arg**, int, lo_message_*, void*)'} [-fpermissive]
  266 |   lo_server_add_method(m_osc_server, NULL, NULL, OSCDataHandler, this);
      |                                                  ^~~~~~~~~~~~~~
      |                                                  |
      |                                                  int (*)(const char*, const char*, lo_arg**, int, void*, void*)
In file included from /usr/include/lo/lo.h:32,
                 from ./plugins/osc/OSCNode.h:24:
/usr/include/lo/lo_lowlevel.h:876:72: note:   initializing argument 4 of 'lo_method_* lo_server_add_method(lo_server, const char*, const char*, lo_method_handler, const void*)'
  876 |                                const char *typespec, lo_method_handler h,
      |                                                      ~~~~~~~~~~~~~~~~~~^
make[2]: *** [Makefile:12250: plugins/osc/libolaoscnode_la-OSCNode.lo] Error 1
make[2]: Leaving directory '/home/tobiasb/.cache/rua/build/ola/src/ola-0.10.9'
make[1]: *** [Makefile:16480: all-recursive] Error 1
make[1]: Leaving directory '/home/tobiasb/.cache/rua/build/ola/src/ola-0.10.9'
make: *** [Makefile:7553: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```

during the build.
Is someone else having this, too?

### PR DESCRIPTION
**Pull request by cbix**
- Fixes #1949 
- Doesn't break building with liblo 0.31
- 0.32 also introduces address pattern matching, which could make the `OSCNode` code even simpler (?)

### CODE REVIEW

File: plugins/osc/OSCNode.cpp [hunk 1]
```diff
@@ -150,7 +150,7 @@ int OSCDataHandler(const char *osc_address, const char *types, lo_arg **argv,
 
   if (argc == 1) {
     if (type == "b") {
-      lo_blob blob = argv[0];
+      lo_blob blob = (lo_blob)argv[0];
```
Comment (cbix) [inline plugins/osc/OSCNode.cpp:153]: Example code in liblo also uses a regular typecast:

https://github.com/radarsat1/liblo/blob/c1a51bca21e8535ce77a9daf256f2e74c1a7e80f/examples/example_server.c#L125

**Review by kripton — APPROVED** [review]
Hi, and thanks for the fix. I was looking for some VERSION symbol in liblo's headers so we could check which version we are building against. However, only a function is provided.
I can confirm that the fix works fine with liblo-0.31 and liblo-0.32, thus I approve the changes.

@peternewman  and @nomis52 : Are any older versions of liblo known that we might need to support and that would not compile with these changes?

**Comment by cbix** [comment]
CI debian sid failure seems unrelated:
```
autopkgtest [20:52:13]: test command3: set -e ; for py in $(py3versions -s 2>/dev/null) ; do echo "Testing with $py:" ; $py $(which rdm_responder_test.py) --help ; done
autopkgtest [20:52:13]: test command3: [-----------------------
Testing with python3.12:
bash: line 1: python3.12: command not found
autopkgtest [20:52:14]: test command3: -----------------------]
autopkgtest [20:52:14]: test command3:  - - - - - - - - - - results - - - - - - - - - -
command3             FAIL non-zero exit status 127
```

**Comment by kripton** [comment]
> CI debian sid failure seems unrelated:
> 
> ```
> autopkgtest [20:52:13]: test command3: set -e ; for py in $(py3versions -s 2>/dev/null) ; do echo "Testing with $py:" ; $py $(which rdm_responder_test.py) --help ; done
> autopkgtest [20:52:13]: test command3: [-----------------------
> Testing with python3.12:
> bash: line 1: python3.12: command not found
> autopkgtest [20:52:14]: test command3: -----------------------]
> autopkgtest [20:52:14]: test command3:  - - - - - - - - - - results - - - - - - - - - -
> command3             FAIL non-zero exit status 127
> ```

Yes, indeed, that python3.12-related failure is not new, so nothing you broke :)

**Comment by peternewman** [comment]
> Hi, and thanks for the fix. I was looking for some VERSION symbol in liblo's headers so we could check which version we are building against. However, only a function is provided.

Yeah sadly nothing easy like that and they haven't bumped in such a way we could detect a breaking ABI change either.

> I can confirm that the fix works fine with liblo-0.31 and liblo-0.32, thus I approve the changes.
> @peternewman and @nomis52 : Are any older versions of liblo known that we might need to support and that would not compile with these changes?

I've got an old box with liblo-0.28 still kicking about and it built fine on there too, so I think we're probably fine from that perspective.

**Review by peternewman — APPROVED** [review]
Thanks @cbix LGTM/still compiles for me on an older version.

It would be good to get this into 0.10 branch too, but one of us can cherry-pick/backport it if you don't want to rebase onto there.

Just to have a note of it, have you (or indeed @kripton ) tested the OSC functionality with this patch or just that it compiles?

**Comment by cbix** [comment]
> have you tested the OSC functionality

not 100 % sure how to test it, I just started olad and ran a [python-osc example](https://github.com/attwad/python-osc/blob/master/examples/simple_client.py) against its port 7770, couldn't observe any issues or errors but also nothing happens inside `ola_dmxmonitor`

**Comment by peternewman** [comment]
Perfect thanks @cbix !

Do you want to try and rebase this onto the 0.10 branch, otherwise we can merge what you've got and backport it ourselves?

**Comment by cbix** [comment]
@peternewman done :)

**Review by peternewman — APPROVED** [review]
LGTM thanks @cbix 💯 !

**Comment by kripton** [comment]
Would it be possible to release an 0.10.10 with that fix?
