### PR TITLE
Various fixes

### LINKED ISSUE #812: RDM NACK codes aren't correctly reported in 0.9.6
As mentioned here:
https://groups.google.com/d/msg/open-lighting/ra-jK5hZ8z4/f2cFHDTNUrgJ

It seems to be this commit:
https://github.com/OpenLightingProject/ola/commit/d971464004622c777af6062e6fa1eff122818345#diff-d63f9b92a627a457f40db37fa20e6550L317

Is there any reason we've dropped NackReason or not added one to RDMResponse? If we're not going to go down that route, I guess we just need a NetworkToHost around the ParamData call, but it would be nice to put it server/API side rather than client.

### PR DESCRIPTION
**Pull request by nomis52**
Fix the little endian bug in the shownet code
Clean up the debian metadata files.
Fix the endian bug in the C++ RDM client - closes #812

### CODE REVIEW

File: examples/ola-rdm.cpp [hunk 1]
```diff
@@ -315,7 +317,7 @@ void RDMController::HandleResponse(const ola::client::Result &result,
     } else {
       memcpy(reinterpret_cast<uint8_t*>(&backoff_time), response->ParamData(),
              sizeof(backoff_time));
-      unsigned int timeout = 100 * backoff_time;
+      unsigned int timeout = 100 * NetworkToHost(backoff_time);
```
Comment (peternewman) [inline examples/ola-rdm.cpp]: This is feeling more and more to me like we should be providing a method as part of RDMResponse to do most of the leg work for you; it's a lot of potential for bugs for someone to implement in their own client.

Comment (nomis52) [inline examples/ola-rdm.cpp]: Maybe, that doesn't belong in the 0.9 branch though.

File: examples/ola-rdm.cpp [hunk 2]
```diff
@@ -349,6 +351,7 @@ void RDMController::HandleResponse(const ola::client::Result &result,
     } else {
       memcpy(reinterpret_cast<uint8_t*>(&nack_reason), response->ParamData(),
              sizeof(nack_reason));
+      nack_reason = NetworkToHost(nack_reason);
```
Comment (peternewman) [inline examples/ola-rdm.cpp]: Likewise here.

File: plugins/shownet/ShowNetNode.cpp [hunk 3]
```diff
@@ -321,16 +321,18 @@ unsigned int ShowNetNode::BuildCompressedPacket(shownet_packet *packet,
...
+  compressed_dmx->slotSize[0] = HostToLittleEndian(
+      static_cast<uint16_t>(buffer.Size()));
 
   unsigned int enc_len = sizeof(packet->data);
   if (!m_encoder.Encode(buffer, compressed_dmx->data, &enc_len))
     OLA_WARN << "Failed to encode all data (used " << enc_len << " bytes";
 
-  compressed_dmx->indexBlock[0] = HostToLittleEndian(MAGIC_INDEX_OFFSET);
+  compressed_dmx->indexBlock[0] = HostToLittleEndian(
+      static_cast<uint16_t>(MAGIC_INDEX_OFFSET));
```
Comment (peternewman) [inline plugins/shownet/ShowNetNode.cpp]: I'm kind of surprised this needs the cast, or does it get treated as an int otherwise?

File: debian/control [hunk 4]
```diff
@@ -19,7 +19,7 @@ Description: Open Lighting Architecture - development libraries
  effects.
  .
  The Open Lighting Architecture (OLA) provides a plugin framework for
- distributing DMX512 control signals on Mac and Linux.
```
Comment (peternewman) [inline debian/control]: Good call.

File: plugins/shownet/ShowNetNode.cpp (hunk 3 above)
Comment (nomis52) [inline plugins/shownet/ShowNetNode.cpp]: It doesn't, this is defensive in case anyone changes the type later.

File: examples/ola-rdm.cpp (hunk 1 above)
Comment (peternewman) [inline examples/ola-rdm.cpp]: Okay.

File: plugins/shownet/ShowNetNode.cpp (hunk 3 above)
Comment (peternewman) [inline plugins/shownet/ShowNetNode.cpp]: Ah okay, presumably they were all being treated as ints before and hence breaking?

**Comment by peternewman** [comment]
LGTM

File: plugins/shownet/ShowNetNode.cpp (hunk 3 above)
Comment (nomis52) [inline plugins/shownet/ShowNetNode.cpp]: Yup
